### ISSUE TITLE
Use load_or_create_experiment from QCoDeS, not select_experiment from pytopo

### ISSUE THREAD

**Issue by LGruenhaupt** [damazter/pysweep#18]
pysweep uses: 
from pytopo.qctools.dataset2 import select_experiment.

On import the following warning occurs:
```
C:\ProgramData\Anaconda3\lib\site-packages\qcodes\dataset\sqlite_base.py:51: UserWarning: The module `qcodes.dataset.sqlite_base` is deprecated.
Public features are available at the import of `qcodes`.
Private features are available in `qcodes.dataset.sqlite.*` modules.
  warnings.warn('The module `qcodes.dataset.sqlite_base` is deprecated.\n'
```

This concerns the functions
 from qcodes.dataset.sqlite_base import transaction, one

which moved now to:
from qcodes.dataset.sqlite.queries import one
from qcodes.dataset.sqlite.connection import transaction

A fix is to take care of this in pytopo. However, then one still depends on pytopo. 

**Therefore, the preferred solution would be to move the function into pysweep/databackend (or something), which would get rid of the deprecation warning and remove the dependency on pytopo**
 
```
from qcodes.dataset.experiment_container import load_experiment_by_name, \
    new_experiment

def select_experiment(exp_name, sample_name):
    """
    Convenience function that will check if the experiment/sample
    combination already exists in the current database. If so,
    it'll return the existing one. Otherwise it will create a new
    one and return that.

    Potential issue: if multiple experiments with the same
    experiment/sample combination exist, our detection method will
    fail, and another copy of this combination will be created.
    """
    try:
        exp = load_experiment_by_name(exp_name, sample_name)
    except ValueError:
        exp = new_experiment(exp_name, sample_name)
    return exp
```

**Comment by astafan8** [comment]
> ... the preferred solution would be to move the function into pysweep/databackend
@LGruenhaupt, sorry, no :) The preferred solution is to [use a feature from qcodes that has been there for already long time and does exactly the same, here is the doc about it](https://qcodes.github.io/Qcodes/examples/15_minutes_to_QCoDeS.html#Load-or-create-experiment).

But thanks for calling this out. unfortunately [removing these functions from pytopo as noted in this issue on the pytopo repo](https://github.com/kouwenhovenlab/pytopo/issues/6) is still pending.

**Comment by damazter** [comment]
I will update the example notebook after PR #19 is merged

**Comment by LGruenhaupt** [comment]
> @LGruenhaupt, sorry, no :) The preferred solution is to [use a feature from qcodes that has been there for already long time and does exactly the same, here is the doc about it](https://qcodes.github.io/Qcodes/examples/15_minutes_to_QCoDeS.html#Load-or-create-experiment).
> 
> But thanks for calling this out. unfortunately [removing these functions from pytopo as noted in this issue on the pytopo repo](https://github.com/kouwenhovenlab/pytopo/issues/6) is still pending.

@astafan8 
Fair enough, this is indeed a much better solution :+1:
